---
# main Anaconda download server
anaconda_mirror : 'http://repo.continuum.io/archive'

# version of python (2|3)
anaconda_python_ver : '3'

# anaconda version
anaconda_ver : '4.2.0'

# anaconda plataform
anaconda_platform : 'x86_64'

# when downloading the anaconda binary it might take a while
# don't let you less great network connection cause the roll to falter
anaconda_timeout_seconds : 600

# add the anaconda python onto the front of your path.
# Caveat Emptor: if you're OS package manager is python based careful about jamming it
anaconda_make_sys_default : false

# when installed inside a container delete all of the installer artifacts. won't be
# idempotent but will be small in terms of layer/image size
anaconda_cleanup : false

# conda packages to install
anaconda_pkg_list : [pandas,scikit-learn]

anaconda_name : 'Anaconda{{anaconda_python_ver}}-{{anaconda_ver}}-Linux-{{anaconda_platform}}'

anaconda_installer_sh : '{{anaconda_name}}.sh'

anaconda_installer_url : '{{anaconda_mirror}}/{{anaconda_installer_sh}}'
