---
- name: download installer.sh
  become: yes
  become_user: root
  get_url: >
    url={{anaconda_installer_url}}
    dest=/tmp/{{anaconda_installer_sh}}
    mode=0755
    timeout={{anaconda_timeout_seconds}}

- name: installing conda
  become: yes
  become_user: root
  command: /tmp/{{anaconda_installer_sh}} -b -p /opt/{{anaconda_name}}
  args:
    creates: /opt/{{anaconda_name}}/bin/conda

- name: deleting installer...
  become: yes
  become_user: root
  when: anaconda_cleanup
  file:
    path=/tmp/{{anaconda_installer_sh}}
    state=absent

- name: link anaconda...
  become: yes
  become_user: root
  file:
    dest=/opt/anaconda
    src=/opt/{{anaconda_name}}
    state=link

- name: install additional packages...
  become: yes
  become_user: root
  command: /opt/anaconda/bin/conda install -y {{item}}
  with_items: '{{ anaconda_pkg_list }}'

- name: conda updates
  become: yes
  become_user: root
  command: /opt/anaconda/bin/conda update -y --all

- name: remove conda-curl since it conflicts with the system curl
  become: yes
  become_user: root
  command: /opt/anaconda/bin/conda remove -y curl
  args:
    removes: /opt/anaconda/lib/libcurl.a

- name: make system default python etc...
  become: yes
  become_user: root
  when: anaconda_make_sys_default
  copy: >-
    src=etc/profile.d/anaconda.sh
    dest=/etc/profile.d/anaconda.sh
    mode=0644

- name: add anaconda to the PATH
  sudo: false
  shell: "echo '{{ item }}' >> ~/.bashrc executable=/bin/bash"
  with_items:
  - "export PATH=/opt/anaconda/bin:$PATH"
